# Generated by Django 6.1.1 on 2026-10-05 12:39

import apps.accounts.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('web', 'Web Browser'), ('android', 'Android PWA'), ('ios', 'iOS Safari')], default='web', max_length=32)),
                ('app_version', models.CharField(default='1.0.0', max_length=32)),
                ('analytics_opt_in', models.BooleanField(default=False, help_text='Explicit user opt-in required for anonymous telemetry.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, help_text='Associated user if this device is authenticated.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20, validators=[apps.accounts.validators.validate_e164_phone])),
                ('relationship', models.CharField(choices=[('family', 'Family'), ('friend', 'Friend'), ('caregiver', 'Caregiver / Assistant'), ('medical', 'Doctor / Clinic'), ('other', 'Other')], default='family', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='accounts.device')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('hi', 'हिन्दी (Hindi)')], default='en', max_length=8)),
                ('speech_rate', models.FloatField(default=1.0, validators=[apps.accounts.validators.validate_speech_rate])),
                ('volume', models.FloatField(default=1.0, validators=[apps.accounts.validators.validate_volume])),
                ('spatial_beeps', models.BooleanField(default=True)),
                ('alert_distance_m', models.FloatField(default=5.0, validators=[apps.accounts.validators.validate_alert_distance])),
                ('vibration', models.BooleanField(default=True)),
                ('low_power', models.BooleanField(default=False)),
                ('calm_mode', models.BooleanField(default=False)),
                ('model_size', models.CharField(choices=[('nano', 'YOLO Nano (Fastest, low battery)'), ('small', 'YOLO Small (Higher accuracy)')], default='nano', max_length=16)),
                ('detection_mode', models.CharField(choices=[('on_device', 'On-Device (Private, 100% offline)'), ('cloud', 'Cloud Assisted (Server inference & OCR)')], default='on_device', max_length=16)),
                ('fall_detection_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='accounts.device')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Settings',
                'verbose_name_plural': 'User Settings',
            },
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['user', 'last_seen'], name='accounts_de_user_id_cc5d73_idx'),
        ),
        migrations.AddIndex(
            model_name='emergencycontact',
            index=models.Index(fields=['user', 'created_at'], name='accounts_em_user_id_ebb4e8_idx'),
        ),
        migrations.AddIndex(
            model_name='emergencycontact',
            index=models.Index(fields=['device', 'created_at'], name='accounts_em_device__8e14d5_idx'),
        ),
        migrations.AddConstraint(
            model_name='emergencycontact',
            constraint=models.CheckConstraint(condition=models.Q(('user__isnull', False), ('device__isnull', False), _connector='OR'), name='contact_must_belong_to_user_or_device'),
        ),
        migrations.AddConstraint(
            model_name='usersettings',
            constraint=models.CheckConstraint(condition=models.Q(('user__isnull', False), ('device__isnull', False), _connector='OR'), name='settings_must_belong_to_user_or_device'),
        ),
    ]
