# Generated by Django 6.1.1 on 2026-10-05 13:19

import apps.modelhub.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text="Semantic version string, e.g. 'v1.0.0'", max_length=32, unique=True)),
                ('model_type', models.CharField(choices=[('onnx_web', 'ONNX Web (Client In-Browser)'), ('yolo_pt', 'PyTorch YOLO (Server Inference)'), ('tflite', 'TFLite (Mobile Optimized)'), ('tensorrt', 'TensorRT (Edge Acceleration)')], default='onnx_web', max_length=32)),
                ('weights_file', models.FileField(upload_to=apps.modelhub.models.model_weights_path)),
                ('sha256_checksum', models.CharField(blank=True, db_index=True, max_length=64)),
                ('min_app_version', models.CharField(default='1.0.0', max_length=32)),
                ('imgsz', models.IntegerField(default=416, help_text='Inference image resolution (e.g. 320, 416, 640)')),
                ('is_active', models.BooleanField(db_index=True, default=False, help_text='If checked, this version is served as the active production model for its type.')),
                ('release_notes', models.TextField(blank=True, default='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Model Version',
                'verbose_name_plural': 'Model Versions',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
