"""
Models for Netra Analytics, Usage Telemetry, and Safety Incidents.
Provides:
- UsageEvent: Privacy-first, opt-in anonymous telemetry (sessions, hazard counts)
- DailyAnalyticsSummary: Pre-aggregated daily metrics compiled by Celery beat
- SafetyIncident: Fall detection / emergency distress events with pre-formatted WhatsApp & SMS contact links
"""
import uuid
import urllib.parse
from django.db import models
from django.conf import settings
from django.utils import timezone


class UsageEvent(models.Model):
    """
    Opt-in, anonymous usage telemetry. Strictly decoupled from PII.
    Automatically purged after 30 days by Celery beat.
    """
    EVENT_TYPE_CHOICES = [
        ('session_start', 'Navigation Session Started'),
        ('session_end', 'Navigation Session Ended'),
        ('hazard_detected', 'Hazard Detected & Warned'),
        ('speech_played', 'Voice Announcement Spoken'),
        ('ocr_used', 'OCR Text Sign Extraction'),
        ('describe_used', 'Natural Scene Description'),
    ]

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    device_id = models.CharField(max_length=64, db_index=True)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='usage_events'
    )
    event_type = models.CharField(max_length=32, choices=EVENT_TYPE_CHOICES, db_index=True)
    event_data = models.JSONField(
        default=dict,
        blank=True,
        help_text="Metrics such as session duration, average FPS, latency, or obstacle class."
    )
    timestamp = models.DateTimeField(default=timezone.now, db_index=True)

    class Meta:
        ordering = ['-timestamp']
        verbose_name = 'Usage Event'
        verbose_name_plural = 'Usage Events'

    def __str__(self) -> str:
        return f"{self.get_event_type_display()} ({self.device_id[:8]})"


class DailyAnalyticsSummary(models.Model):
    """
    Aggregated daily metrics generated by Celery background jobs.
    Allows rapid admin dashboards without querying millions of raw telemetry rows.
    """
    date = models.DateField(unique=True, db_index=True)
    total_sessions = models.IntegerField(default=0)
    total_hazards_detected = models.IntegerField(default=0)
    total_incidents = models.IntegerField(default=0)
    unique_devices = models.IntegerField(default=0)
    average_fps = models.FloatField(default=0.0)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-date']
        verbose_name = 'Daily Analytics Summary'
        verbose_name_plural = 'Daily Analytics Summaries'

    def __str__(self) -> str:
        return f"Summary {self.date}: {self.total_sessions} sessions, {self.total_hazards_detected} hazards"


class SafetyIncident(models.Model):
    """
    Critical safety events: Phone fall detection via accelerometer,
    inactivity timeout, or manual panic trigger.
    """
    INCIDENT_TYPE_CHOICES = [
        ('fall_detected', 'Fall Detected (Sudden Accelerometer Impact)'),
        ('panic_button', 'Emergency Panic Trigger'),
        ('inactivity_timeout', 'Prolonged Inactivity (60s No Movement)'),
    ]

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    device_id = models.CharField(max_length=64, db_index=True)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='safety_incidents'
    )
    incident_type = models.CharField(max_length=32, choices=INCIDENT_TYPE_CHOICES, default='fall_detected')
    latitude = models.DecimalField(max_digits=9, decimal_places=6, null=True, blank=True)
    longitude = models.DecimalField(max_digits=9, decimal_places=6, null=True, blank=True)
    resolved = models.BooleanField(default=False, db_index=True)
    created_at = models.DateTimeField(auto_now_add=True, db_index=True)

    class Meta:
        ordering = ['-created_at']
        verbose_name = 'Safety Incident'
        verbose_name_plural = 'Safety Incidents'

    def __str__(self) -> str:
        status = " [RESOLVED]" if self.resolved else " [ALERT]"
        return f"{self.get_incident_type_display()} ({str(self.id)[:8]}){status}"

    def generate_emergency_links(self, contact_phone: str, contact_name: str = "") -> dict:
        """
        Builds ready-to-open WhatsApp and SMS URLs with GPS location for emergency contacts.
        """
        # Format clean digits for WhatsApp (removes +, spaces, dashes)
        clean_phone = ''.join(c for c in contact_phone if c.isdigit())

        # Construct location string
        loc_str = ""
        if self.latitude is not None and self.longitude is not None:
            map_url = f"https://maps.google.com/?q={self.latitude},{self.longitude}"
            loc_str = f" My location: {map_url}"

        # Emergency message text
        display_name = contact_name or "Family"
        msg = f"EMERGENCY: Netra detected a safety incident ({self.get_incident_type_display()}) for me.{loc_str} Please check on me immediately."

        encoded_msg = urllib.parse.quote(msg)

        whatsapp_url = f"https://wa.me/{clean_phone}?text={encoded_msg}"
        sms_url = f"sms:{clean_phone}?body={encoded_msg}"

        return {
            "contact_phone": contact_phone,
            "contact_name": contact_name,
            "message": msg,
            "whatsapp_url": whatsapp_url,
            "sms_url": sms_url,
        }
