# Generated by Django 6.1.1 on 2026-10-05 13:19

import apps.feedback.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(db_index=True, max_length=64)),
                ('image', models.ImageField(upload_to=apps.feedback.models.report_image_path)),
                ('issue_type', models.CharField(choices=[('missed_obstacle', 'Missed Obstacle (Did not detect hazard)'), ('false_alarm', 'False Alarm (Detected phantom obstacle)'), ('wrong_distance', 'Incorrect Distance Estimation'), ('wrong_label', 'Misclassified Object Name'), ('other', 'Other Issue / Feedback')], default='missed_obstacle', max_length=32)),
                ('user_note', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Telemetry including detected bounding boxes, client app version, and sensor data.')),
                ('is_reviewed', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Detection Report',
                'verbose_name_plural': 'Detection Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
