# Generated by Django 6.1.1 on 2026-10-05 13:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAnalyticsSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('total_sessions', models.IntegerField(default=0)),
                ('total_hazards_detected', models.IntegerField(default=0)),
                ('total_incidents', models.IntegerField(default=0)),
                ('unique_devices', models.IntegerField(default=0)),
                ('average_fps', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Daily Analytics Summary',
                'verbose_name_plural': 'Daily Analytics Summaries',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SafetyIncident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(db_index=True, max_length=64)),
                ('incident_type', models.CharField(choices=[('fall_detected', 'Fall Detected (Sudden Accelerometer Impact)'), ('panic_button', 'Emergency Panic Trigger'), ('inactivity_timeout', 'Prolonged Inactivity (60s No Movement)')], default='fall_detected', max_length=32)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('resolved', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safety_incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Safety Incident',
                'verbose_name_plural': 'Safety Incidents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UsageEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(db_index=True, max_length=64)),
                ('event_type', models.CharField(choices=[('session_start', 'Navigation Session Started'), ('session_end', 'Navigation Session Ended'), ('hazard_detected', 'Hazard Detected & Warned'), ('speech_played', 'Voice Announcement Spoken'), ('ocr_used', 'OCR Text Sign Extraction'), ('describe_used', 'Natural Scene Description')], db_index=True, max_length=32)),
                ('event_data', models.JSONField(blank=True, default=dict, help_text='Metrics such as session duration, average FPS, latency, or obstacle class.')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usage Event',
                'verbose_name_plural': 'Usage Events',
                'ordering': ['-timestamp'],
            },
        ),
    ]
